const MarketData = [
  {
    title: "Produit 1",
    image: "produit1.png",
    mark: "Marque A",
    des: "lorem ipsum dolor sit amet ipsum dolor sit amet, ipsum dolor sit amet lorem ipsum dolor sit amet ipsum dolor sit amet",
    price: "2100",
  },
  {
    title: "Produit 2",
    image: "produit2.jpg",
    mark: "Marque B",
    des: "lorem ipsum dolor sit amet ipsum dolor sit amet, ipsum dolor sit amet lorem ipsum dolor sit amet ipsum dolor sit amet",
    price: "1500",
  },
  {
    title: "Produit 3",
    image: "produit3.jpg",
    mark: "Marque C",
    des: "lorem ipsum dolor sit amet ipsum dolor sit amet, ipsum dolor sit amet lorem ipsum dolor sit amet ipsum dolor sit amet",
    price: "1000",
  },
  {
    title: "Produit 4",
    image: "produit4.jpg",
    mark: "Marque D",
    des: "lorem ipsum dolor sit amet ipsum dolor sit amet, ipsum dolor sit amet lorem ipsum dolor sit amet ipsum dolor sit amet",
    price: "2300",
  },
  {
    title: "Produit 5",
    image: "produit5.png",
    mark: "Marque E",
    des: "lorem ipsum dolor sit amet ipsum dolor sit amet, ipsum dolor sit amet lorem ipsum dolor sit amet ipsum dolor sit amet",
    price: "600",
  },
  {
    title: "Produit 6",
    image: "produit6.jpeg",
    mark: "Marque F",
    des: "lorem ipsum dolor sit amet ipsum dolor sit amet, ipsum dolor sit amet lorem ipsum dolor sit amet lorem ipsum dolor sit amet",
    price: "210",
  },
  {
    title: "Produit 7",
    image: "produit7.jpg",
    mark: "Marque X",
    des: "lorem ipsum dolor sit amet ipsum dolor sit amet, ipsum dolor sit amet lorem ipsum dolor sit amet",
    price: "1200",
  },
  {
    title: "Produit 8",
    image: "produit8.jpg",
    mark: "Marque G",
    des: "lorem ipsum dolor sit amet ipsum dolor sit amet, ipsum dolor sit amet lorem ipsum dolor sit amet",
    price: "1100",
  },
  {
    title: "Produit 9",
    image: "produit9.png",
    mark: "Marque H",
    des: "lorem ipsum dolor sit amet ipsum dolor sit amet, ipsum dolor sit amet lorem ipsum dolor sit amet",
    price: "850",
  },
];
export default MarketData;
